In [10]:
import pandas as pd

In [11]:
dataset = pd.read_csv("Preprocessed_Placement.csv")

In [12]:
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [16]:
dataset.isnull().sum()

sl_no             0
ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [34]:
dataset.drop('sl_no', inplace=True,axis=1)

In [35]:
dataset

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,58.00,60.00,72.00,74.0,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,67.00,67.00,73.00,59.0,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,74.00,66.00,58.00,70.0,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,62.00,58.00,53.00,89.0,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [36]:
	def QuanQual(dataset):
	    Quan=[]
	    Qual=[]
	    for ColumnName in dataset.columns:
	        #print(ColumnName)
	        if (dataset[ColumnName].dtypes=="O"):
	            #print("Qual")
	            Qual.append(ColumnName)
	        else:
	            #print("Quan")
	            Quan.append(ColumnName)
	    return Quan,Qual

In [37]:
QuanQual(dataset)

(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [38]:
Quan, Qual = QuanQual(dataset)

In [39]:
dataset[Quan]

     ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0    67.00  91.00     58.00     55.0  58.80  270000.0
1    79.33  78.33     77.48     86.5  66.28  200000.0
2    65.00  68.00     64.00     75.0  57.80  250000.0
3    56.00  52.00     52.00     66.0  59.43       0.0
4    85.80  73.60     73.30     96.8  55.50  425000.0
..     ...    ...       ...      ...    ...       ...
210  80.60  82.00     77.60     91.0  74.49  400000.0
211  58.00  60.00     72.00     74.0  53.62  275000.0
212  67.00  67.00     73.00     59.0  69.72  295000.0
213  74.00  66.00     58.00     70.0  60.23  204000.0
214  62.00  58.00     53.00     89.0  60.22       0.0

[215 rows x 6 columns]

In [40]:
dataset[Quan].cov()

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
ssc_p,117.228377,60.348373,42.897137,37.659225,24.535952,9.017549e+05
hsc_p,60.348373,118.755706,34.819820,35.461678,22.555846,7.633598e+05
degree_p,42.897137,34.819820,54.151103,21.929469,17.272020,4.651315e+05
etest_p,37.659225,35.461678,21.929469,176.251018,16.886973,3.842344e+05
mba_p,24.535952,22.555846,17.272020,16.886973,34.028376,1.262455e+05
salary,901754.893936,763359.777657,465131.504238,384234.419257,126245.485547,2.395714e+10

In [ ]:
"""
Covariance between degree_p and etest_p is 21.929469, which is Positive covariance
Covariance between etest_p and mba_p is 16.886973, which is Positive covariance
Covariance between ss_p and salary is 901754.893936, which is Large Positive covariance
"""

In [41]:
dataset[Quan].corr()

             ssc_p     hsc_p  degree_p   etest_p     mba_p    salary
ssc_p     1.000000  0.511472  0.538404  0.261993  0.388478  0.538090
hsc_p     0.511472  1.000000  0.434206  0.245113  0.354823  0.452569
degree_p  0.538404  0.434206  1.000000  0.224470  0.402364  0.408371
etest_p   0.261993  0.245113  0.224470  1.000000  0.218055  0.186988
mba_p     0.388478  0.354823  0.402364  0.218055  1.000000  0.139823
salary    0.538090  0.452569  0.408371  0.186988  0.139823  1.000000

In [ ]:
""""
Correlation always lies between -1 and +1.
Correlation between mba_p and salary is 0.139823 Low degree positive correlation (Directly proportional to 13%)
"""